### ISSUE TITLE
seidr aggregate does not parallelise

### ISSUE THREAD

**Issue by nicolasDelhomme** [bschiffthaler/seidr#10]

**Comment by nicolasDelhomme** [comment]
Allocation is:
NumNodes=1 NumCPUs=32 NumTasks=32 CPUs/Task=1 ReqB:S:C:T=0:0:*:*
   TRES=cpu=32,mem=128G,node=1

Code is:
CPU=32
export OMP_NUM_THREADS=$CPU
seidr aggregate -m irp -k -O $CPU $@

It is at the ranking/sorting stage that should parallelise
[ INFO    ][ 2019-03-20T16:36:05 ][ aggregate ]: Done aggregating. Ranking and standardizing aggregated edges

But it only uses 1 CPU 100%

**Comment by bschiffthaler** [comment]
This could have been run on a version that was compiled without PSTL. Trying to reproduce this has been a bit tricky. I'll keep looking but so far it looks like we had a compilation issue, rather than a bug
