### ISSUE TITLE
Incomplete stderr log when running el-ensemble in targeted mode

### ISSUE THREAD

**Issue by nicolasDelhomme** [bschiffthaler/seidr#11]
This is a minor issue. In the stderr log from el-ensemble (when run using the -t option on batch of 1000 genes), not all genes are reported as being "started". See below, quite a few do not reach 1000 (the last batch: 27000 - has 95, so that's OK). The results are however complete and all genes are present. Hence I just report that in case others would wonder. It may otherwise occur too, but I have not tested that.

./el-ensemble-21000.err
998
./el-ensemble-5000.err
999
./el-ensemble-26000.err
994
./el-ensemble-19000.err
1000
./el-ensemble-8000.err
994
./el-ensemble-20000.err
1000
./el-ensemble-15000.err
1000
./el-ensemble-27000.err
95
./el-ensemble-17000.err
1000
./el-ensemble-13000.err
1000
./el-ensemble-23000.err
1000
./el-ensemble-10000.err
1000
./el-ensemble-25000.err
980
./el-ensemble-11000.err
979
./el-ensemble-3000.err
994
./el-ensemble-6000.err
1000
./el-ensemble-18000.err
1000
./el-ensemble-0.err
980
./el-ensemble-2000.err
1000
./el-ensemble-9000.err
980
./el-ensemble-16000.err
995
./el-ensemble-1000.err
997
./el-ensemble-24000.err
1000
./el-ensemble-7000.err
980
./el-ensemble-22000.err
980
./el-ensemble-4000.err
1000
./el-ensemble-12000.err
980
./el-ensemble-14000.err
1000

**Comment by bschiffthaler** [comment]
The new progress bar probably makes this issue moot (although I am pretty sure it was fine in recent builds) so I'm closing for now.
