### ISSUE TITLE
seidr neighbours - allow for lower/uppercase mismatch

### ISSUE THREAD

**Issue by nicolasDelhomme** [bschiffthaler/seidr#15]
When running:

`seidr neighbours -g AT1G01070,At4g01430,AT4G28040 ...`

seidr reports:

[ ERROR   ][ 2019-09-02T12:31:20 ][ seidr ]: Gene At4g01430 not found in header.

Maybe allowing for lower/uppercase mismatches in the gene ID search could be useful (and possibly issue a warning, even if I can't think of any organism that have case sensitive gene IDs.)

**Comment by bschiffthaler** [comment]
Now do-able with `seidr neighbours --case-insensitive` or `seidr neighbours -I`
