### ISSUE TITLE
Warn instead of fail when `seidr neighbours` encounters a gene absent from the header

### ISSUE THREAD

**Issue by nicolasDelhomme** [bschiffthaler/seidr#16]
Maybe the default behaviour of `seidr neighbours` should be to warn about a gene missing in the header rather than fail. 

[ ERROR   ][ 2019-09-02T13:57:48 ][ seidr ]: Gene AT5G40212 not found in header.

Because we typically filter genes prior to generate the network, we cannot assume that all genes might be in the header and as such the ground for the error will rather be a constant than an exception. It does not harm to ignore the missing genes and proceed with the rest of the provided IDs.

**Comment by bschiffthaler** [comment]
I will add a flag (`--lax` ?) for this and #15 
That way the default behaviour is strict with regard to correctness, but users whoa re confident can circumvent it.

**Comment by bschiffthaler** [comment]
Now default behavious for `seidr view` and `seidr neighbours`. You can revert to old behaviour (failure on bad lookup) with `seidr neighbours --strict` or `seidr view --strict`
