### ISSUE TITLE
seidr roc has an incoherent error message

### ISSUE THREAD

**Issue by nicolasDelhomme** [bschiffthaler/seidr#22]
When I ran the following command (which misses the -p for the number of points)

seidr roc -n /mnt/picea/projects/spruce/vhurry/drought-stress-needles/preprosessed/se
idr/backbone/aggregated.sf -g /mnt/picea/storage/reference/goldStandard/Picea-abies_KEG
G-based-positive-gold-standard.tsv -x /mnt/picea/storage/reference/goldStandard/Picea-a
bies_KEGG-based-negative-gold-standard.tsv -a 1000

I got the following error:

[ ERROR   ][ 2020-03-14T15:41:47 ][ seidr ]: option '--network' cannot be sp
ecified more than once

**Comment by bschiffthaler** [comment]
This is because you specify `-n`, but the network can also be positional. Your `-a` is a switch so the CLI thinks the `1000` is also an argument to network. It's possible to code around that in `boost::program_options`, but this is intended behaviour

**Comment by nicolasDelhomme** [comment]
Then I think the man page (seidr roc) should say so. It says that -n is required, so I do not expect any positional argument :-)

I think it might get others confused too ;-)

**Comment by bschiffthaler** [comment]
Forgot to tag, this is mentioned in the usage message now since 720c6a5b415e5296fbc8a1efe4f74daba93ad0e8
