### ISSUE TITLE
Reversed exemple for the SD in seidr backbone -help

### ISSUE THREAD

**Issue by Ayllonbe** [bschiffthaler/seidr#24]
for seidr backbone -help, for the flag -F said that: Subset network to edges with at least this SD. 1.28, 1.64, and 2.32 correspond to ~P0.01, 0.05 and 0.1. In fact,
2.32 correspond to qnorm(0.99) that is the 1% and 1.28 to qnorm(0.9) that is 10% so the proposed example is reversed.

**Comment by bschiffthaler** [comment]
Ordered both the same in 5e59272
