### ISSUE TITLE
tomsimilarity default sft-cutoff value incorrect

### ISSUE THREAD

**Issue by loalon** [bschiffthaler/seidr#33]
tomsimilarity help screen prints a sft-cutoff default value of TOM_DEF_FIT, where it should be 0.8.

This bug seems to only affect the help screen, the issue is probably in tomsimilarity.cpp, line 87

**Comment by bschiffthaler** [comment]
This is probably true for many (if not most help screens). Looks like this macro works if `TOM_DEF_FIT` is also a macro, but to make typing more consistent, these were all changed recently be `constexpr`:

Works

```c++
#define TOM_DEF_FIT 0.8
default_value(TOM_DEF_FIT, _XSTR(TOM_DEF_FIT))
``

Doesn't

```c++
constexpr double TOM_DEF_FIT = 0.8;
default_value(TOM_DEF_FIT, _XSTR(TOM_DEF_FIT))
``

We can do something like this to print a nice looking string repr:

```c++
template<typename T>
std::string to_rounded_str(T s, uint64_t digits = 2) {
  std::stringstream ss;
  ss << std::setprecision(digits);
  ss << s;
  return ss.str();
}
```
