### ISSUE TITLE
seidr ROC output file closed prematurely

### ISSUE THREAD

**Issue by krbe9202** [bschiffthaler/seidr#36]
When running the runSeidrRoc.sh script from UPSCb-common, the output in ROC file for the aggregated network (sf file in `/mnt/picea/home/kbenevides/Git/arabidopsis-porcupine-networks/data/seidr/aggregated`) stopped unexpectedly at one row (finished 12563 out of 13039 rows), yet the script completed with exit code 0. It worked fine for the backbone networks.

**Comment by krbe9202** [comment]
I'm sorry haha I'm so stupid, I didn't check the correct log file (I checked for the submitAggregated), but the problem was due to the time limit (4 hours). No bug!

**Comment by bschiffthaler** [comment]
You were right though. The `std::ostream` is not flushed on exit. In most cases that shouldn't matter, but it could, so I'll fix that. Thanks for the report.

Line: https://github.com/bschiffthaler/seidr/blob/devel/src/Seidr/roc.cpp#L483
Should have

```c++
out->flush();
f.close();
```
