### ISSUE TITLE
ARACNE throwing only 0 values 

### ISSUE THREAD

**Issue by gianfilippo** [bschiffthaler/seidr#45]
Hi,

I am running a script like in your tutorial. My data are batch corrected and have negative values. I am running with a target file

mi -t $dataDIR/$targetFILE -m ARACNE -i $dataDIR/$exprFILE -g $dataDIR/$geneFILE -M $outDIR/mi_full_scores.tsv -o $outDIR/aracne_scores.tsv

The output for ARACNE has only zeroes. Is there a problem with inputting data with negative values ?

Thanks

**Comment by bschiffthaler** [comment]
If possible, could you share your data or an MRE?

**Comment by gianfilippo** [comment]
Hi,
here it is
Thanks
[expression.tsv.txt.zip](https://github.com/bschiffthaler/seidr/files/7884853/expression.tsv.txt.zip)

**Comment by gianfilippo** [comment]
Hi,

an update/correction to my original issue.

I took a better look at the output and ARACNE, in reality, has a few non-zero weight edges, specifically I get 272 non-zero weights out of 1174896.
So, it is not really all zeros. Probably only very conservative ?
Other algos also generate a considerable number of zero weight edges, but definitely no as few. For instance, Tigress gives me 29965 non-zero out of 1174895, and elnet 87206 non-zero out of 1174896, definiely more reasonable.

Best

**Comment by bschiffthaler** [comment]
ARACNe is _very_ sparse, so I suspected something like this. Especially if you select only certain targets you will see very few links predicted. I'd leave it out of the ensemble for your use-case to be honest

**Comment by gianfilippo** [comment]
yes, at this point I will be leaving it out
Thanks
